SELECT product_name FROM ORDER_SCHEMA.ORDERS
    JOIN ORDER_SCHEMA.CUSTOMERS ON ORDER_SCHEMA.CUSTOMERS.ID = ORDER_SCHEMA.ORDERS.CUSTOMER_ID
    WHERE UPPER(ORDER_SCHEMA.CUSTOMERS.NAME) = UPPER(:name);