CREATE SCHEMA ORDER_SCHEMA;

CREATE TABLE ORDER_SCHEMA.CUSTOMERS(
    id SERIAL PRIMARY KEY,
    name VARCHAR,
    surname VARCHAR,
    age INT,
    phone_number VARCHAR
)

CREATE TABLE ORDER_SCHEMA.ORDERS(
    id SERIAL PRIMARY KEY,
    date VARCHAR DEFAULT CURRENT_TIMESTAMP,
    customer_id INT,
    product_name VARCHAR,
    amount INT,
    FOREIGN KEY (customer_id) REFERENCES ORDER_SCHEMA.CUSTOMERS(id)
)

